config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  root to: 'lists#index'
  resources :lists, only: %i[index show new create] do
    resources :bookmarks
    resources :movies
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, presence: true, length: { minimum: 6, message: 'should not be shorter than 6' }
  validates :movie_id, uniqueness: { scope: :list_id }
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, :overview, presence: true
  validates :title, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Movies added to list!'
      # Handle successful bookmark creation (e.g., redirect, flash message)
    else
      # Handle errors (e.g., render the form again with error messages)
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully deleted', status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  def index
    @lists = List.all
  end

  def show
    @list = List.find(params[:id])
    # @movies = @list.movies # finding movies asssociated with the lists
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    @list.save

    redirect_to list_path(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<h3>Add a bookmark to <%= @list.name %> list</h3>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: Movie.all %>
  <%= f.input :comment %>
  <%= f.submit %>
<% end %>

<%= link_to 'Back', :lists %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/index.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
</nav>
<!--Masthead-->
<header class="masthead">
  <div class="container">
    <div class="card d-flex align-items-center justify-content-center mt-10 mb-10">
      <h1 class="masthead-subheading">Movie Watchlist</h1>
      <div class="btn btn-info btn-xl text-uppercase" href="#watchlist">
        <%= link_to 'Create new Watchlist', new_list_path(@list) %>
      </div>
    </div>
  </div>
</header>
<!--Lists-->
<div class="row m-5">
  <div class="d-flex align-items-center">
    <div class="d-flex justify-content-between">
        <ul>
          <% @lists.each do |list| %>
          <div class="card">
          <%= link_to list.name, list_path(list) %>
          </div>
          <% end %>
        </ul>
    </div>
  </div>
</div>

app/views/lists/new.html.erb
<h2>Create new Watchlist</h2>

<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

app/views/lists/show.html.erb
<!--add a function that shows the comment written by the user
-->
<div class="container">
  <div class="text-center">
    <h2 class="section-heading text-uppercase"><%= @list.name %></h2>
    <%= link_to 'Add a movie to list', new_list_bookmark_path(@list) %>
  </div>
  <div class="row">
  <% @list.movies.each do |movie| %>
    <div class="card" style="width: 18rem;">
    <img src="https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8YW5pbWV8ZW58MHx8MHx8fDA%3D" class= "card-img-top"alt="list-title">
      <div class="card-body">
        <% @bookmark = Bookmark.find_by(list: @list, movie: movie) %>
        <p><%= movie.title %></p>
        <p><%= movie.overview %></p>
        <p><%= movie.poster_url %></p>
        <p><%= movie.rating %></p>
        <%= link_to "Delete",
        bookmark_path(@bookmark),
        data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
      %>
      </div>
    </div>
  <% end %>
  </div>
  <%= link_to 'Back to main', lists_path(@list) %>
</div>